---
title: "Heparin in Trauma Patients - Exploratory Analysis"
author: "Brian Gulbis"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    code_folding: hide
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r}
library(tidyverse)
library(plotly)

dirr::get_rds("../data/tidy")
```

```{r}
data_ptt %>%
    left_join(data_patients, by = "millennium.id") %>%
    arrange(millennium.id, lab.datetime) %>%
    mutate(
        time.hr = difftime(lab.datetime, start.datetime, units = "hours"),
        age.grp = case_when(
            age >= 80 ~ "80+",
            age >= 70 ~ "70-79",
            age >= 60 ~ "60-69",
            age >= 50 ~ "50-59",
            TRUE ~ "<50"
        )
    ) %>%
    filter(time.hr <= 72) %>%
    plot_ly() %>%
    add_markers(x = ~time.hr, y = ~lab.result, color = ~age)
```

```{r}
data_ptt %>%
    left_join(data_patients, by = "millennium.id") %>%
    mutate(time.hr = difftime(lab.datetime, start.datetime, units = "hours")) %>%
    filter(time.hr <= 72) %>%
    plot_ly() %>%
    add_markers(x = ~age, y = ~lab.result)
```

```{r}
data_ptt %>%
    left_join(data_patients, by = "millennium.id") %>%
    mutate(time.hr = difftime(lab.datetime, start.datetime, units = "hours")) %>%
    filter(time.hr <= 72) %>%
    mutate(ptt.90 = lab.result > 90) %>%
    filter(!is.na(ptt.90)) %>%
    # mutate_at("ptt.90", factor) %>%
    arrange(millennium.id, desc(ptt.90)) %>%
    distinct(millennium.id, ptt.90, age) %>%
    plot_ly(alpha = 0.6) %>%
    add_histogram(
        x = ~age, 
        color = ~ptt.90, 
        histnorm = "percent",
        autobinx = FALSE,
        xbins = list(start = 20, end = 100, size = 5)) %>%
    layout(barmode = "overlay")
```

```{r}
data_ptt %>%
    mutate(time.hr = difftime(lab.datetime, start.datetime, units = "hours")) %>%
    arrange(millennium.id, lab.datetime) %>%
    group_by(millennium.id) %>%
    filter(
        time.hr <= 72,
        lab.result >= 60,
        lab.result <= 90
    ) %>%
    distinct(millennium.id, .keep_all = TRUE) %>%
    left_join(data_patients, by = "millennium.id") %>%
    plot_ly() %>%
    add_markers(x = ~time.hr, y = ~age)
```

